### ISSUE TITLE
I really like your Call Recorder, I met him through the Magisk Modules.  I have a Realme 5 Pro phone RealmeUi Android 10. Thanks, Continue Updating your modules and Application.  Sorry Anything I'm new to GitHub

### ISSUE THREAD

**Issue by JoseLuiziwuaja** [Magisk-Modules-Repo/callrecorder-axet#1]
I really like your Call Recorder, I met him through the Magisk Modules.  I have a Realme 5 Pro phone RealmeUi Android 10. Thanks, Continue Updating your modules and Application.  Sorry Anything I'm new to GitHub

Eu gosto muito do seu Gravador de Chamadas, eu conheci ele através dos Módulos Magisk. Tenho um telefone Realme 5 Pro RealmeUi Android 10. Thanks, Continue Atualizando seus módulos e Aplicativo. Desculpa Qualquer coisa sou novo no GitHub

**Comment by di72nn** [comment]
I'm glad you find it useful.
Actually, I only created this Magisk module, the app itself is made by [axet](https://gitlab.com/axet/android-call-recorder).
