### ISSUE TITLE
Only my sound is recorded. Tested All source. 1+5T, Android Q, Pixel Experience, magisk 20.4

### ISSUE THREAD

**Issue by eviluess** [Magisk-Modules-Repo/callrecorder-axet#2]
Only my sound is recorded. Tested All source. 1+5T, Android Q, Pixel Experience, magisk 20.4

**Comment by di72nn** [comment]
Run `dumpsys package com.github.axet.callrecorder`. The output should have lines like these:
```
# dumpsys package com.github.axet.callrecorder
...
    requested permissions:
      android.permission.CAPTURE_AUDIO_OUTPUT
...
    install permissions:
      android.permission.CAPTURE_AUDIO_OUTPUT: granted=true
```

**Comment by eviluess** [comment]
Thanks for your reply.
I finally made it work by **wiping all** (6 clean) and **re-installing** the system and everything again.

Now it works, and I can see the two expecting lines after doing "**adb shell dumpsys package com.github.axet.callrecorder**".

If it won't work in future, **what should I do**?

**Here the attempts I tried before I wiped the system**:

* Uninstall Axets_Call_Recorder in Magisk
* Reboot
* Uninstall Call Recorder App
* Reboot
* Install Axets_Call_Recorder in Magisk
* Reboot
* Grant all permission to Call Recorder App
* Tick "Calls Recording" to make it ready for call recording.

====================

I found it not working, so I backed-up all apps to PC, then make all wiped (system, data, media, vendor, ...).
Then I Installed System (Pixel Experience) and Magisk.
And immediately install the Axets_Call_Recorder. It works now.

Then I re-installed all the apps I backed-up to my phone, it still working now.

If it won't work in future, **what should I do**?

**Comment by di72nn** [comment]
Thanks for the detailed instructions.
Seems like some random glitch to me.
