### ISSUE TITLE
Ошибка и тихая запись собеседника.

### ISSUE THREAD

**Issue by BOTROBOTMOD** [Magisk-Modules-Repo/callrecorder-axet#3]
Конфликтует с приложением Google Duo.
Когда звонят мне через google duo, меня не слышат. А вот я звоню всё отлично слышно. Обратил внимание на статусбар, что оно пытается записать google duo звонок, через раз, но записи нету, (вес файла пару килобайт и запись 2 секунды - тишины). Понять не мог из-за чего. Попробовал через шторку отключить шоркат - (запись звонка) и с поймал ошибку приложения - запись звонка. И меня услышали в приложении google duo. Вот с ним - Google Duo запись звонков и конфликтует, то ошибка приложения - (запись звонка), или меня не слышат при входящем звонке в приложении Google Duo. :(
Записывает собеседника слегка тиховато. 
Xiaomi Mi A3 Android One 10 Q.
[форум 4pda](https://4pda.ru/forum/index.php?showtopic=992983&st=60)

**Comment by di72nn** [comment]
"Системный микшер" использовать не нужно было. [В инструкции](https://github.com/Magisk-Modules-Repo/callrecorder-axet#how-to-use) же написано: в приложении root использовать **не нужно**.
Эта опция переписывает **системный файл** `/etc/mixer_paths*.xml` (конкретный файл зависит от прошивки).

Что нужно сделать:
1. Отключить опцию "Системный микшер" (отнять root).
1. Восстановить системный файл (достать из прошивки и заменить или перенакатить прошивку).
1. Перепроверить наличие конфликта и громкость записи.
1. Если проблемы сохранятся, то скорее всего это в [репозиторий приложения](https://gitlab.com/axet/android-call-recorder/).

**Comment by BOTROBOTMOD** [comment]
Всё понял.
Прошивку на днях прошил с нуля, буду пробовать.

вт, 10 нояб. 2020 г., 23:43 Dmitriy Bogdanov <notifications@github.com>:

**Comment by BOTROBOTMOD** [comment]
Я разобрался из-за чего бывает перестаёт записывать разговор.
Во всём виноват (Ok Google). Когда включаешь ассистент (ok google),
приложение перестаёт записывать, отключаешь ассистент (ok google)
приложение начинает записывать с линии.
Если можно, исправишь эту ошибку!

пт, 13 нояб. 2020 г., 22:40 Николай Говша <botrobotmod@gmail.com>:

**Comment by di72nn** [comment]
Это уже к автору приложения (я - только автор модуля для Magisk).
