### ISSUE TITLE
App Crashes When save path is changed to SD card

### ISSUE THREAD

**Issue by subferno** [Magisk-Modules-Repo/callrecorder-axet#4]
I am on Samsung s20, Android 11, Magisk 21.1.

After CallRecorder is installed, I went into the settings to change the file path that I would like the recordings to be saved to. I chose a location on my external SD card and gave the app the requested permissions. The app would crash and refuse to open again. I have to go into Android system menu and clear out all data for this app to be able to launch again. It saves just fine on the phone itself, just not on the external memory card.

**Comment by di72nn** [comment]
Try installing the app normally (not via Magisk). If the problem persists, create an issue in the [app repo](https://gitlab.com/axet/android-call-recorder).
