### ISSUE TITLE
Android 11 Unable to initialize

### ISSUE THREAD

**Issue by maruashok** [Magisk-Modules-Repo/callrecorder-axet#5]
Hi
I am using custom firmware android 11. Tried several different ones. Using magisk module, with your app. Started having problems with recording. Sometimes the app doesn't work. When making a call "CallRecorder: Unable to initialize AudioRecord" pops up.  My understanding is that the app goes to sleep or is pushed out of memory and does not trigger recording on the call. All permissions are given. Work in the background is enabled. Charge saving is turned off. Autorun enabled. Under "About", status is yellow - "Some problems".
Found a chain of actions to get this error:

restarting the phone
Waiting for phone to boot completely axet-call-recorder app
open the dialer and call
I get error "CallRecorder: Unable to initialize AudioRecord" and no recording works.

If you then go into the app, exit \ minimize it - then the recording will work.
I get this error and the recording does not work randomly.
On previous androids (9 and 10) there were no such problems. I asked on the russian forum, I'm not the only one who has problems with the app on android 11.
Please update apk with latest version & additional permission if required to add in permission xmlm

**Comment by di72nn** [comment]
Doesn't seem to be related to the Magisk module, report to the [app repo](https://gitlab.com/axet/android-call-recorder).
