### ISSUE TITLE
[feature request] update to v1.7.14 (220) of com.github.axet.callrecorder

### ISSUE THREAD

**Issue by ghost** [Magisk-Modules-Repo/callrecorder-axet#7]
there is a new version available since 2021-06-01,
the current version is from 2019-11-17.

https://f-droid.org/en/packages/com.github.axet.callrecorder/

the changes are mostly cosmetic, there was a filter added to the recording name screen, 
few bugs in the file naming were fixed, 
r12b dependencies were removed and it uses newer gradle version to build the apk.

I'm aware that f-droid is capable of updating the apk, 
but f-droid app is also a total cr^p, and integrating the apk in the installation is the only way it seems to work since updating the app of magisk seems to result with an unusable dalvik cache entry due to how the way normal installation and repeat magisk set-up both work.. :|

**Comment by di72nn** [comment]
As I [mentioned](https://github.com/Magisk-Modules-Repo/callrecorder-axet/pull/6#issuecomment-962558528), there is [a possible issue](https://gitlab.com/axet/android-call-recorder/-/issues/176) with the latest app version.

> integrating the apk in the installation is the only way it seems to work

You can just [download the apk](https://f-droid.org/repo/com.github.axet.callrecorder_220.apk) and update it on a device without the F-Droid client.

> since updating the app of magisk seems to result with an unusable dalvik cache entry due to how the way normal installation and repeat magisk set-up both work.. :|

I don't think I understand what you're saying here.

**Comment by eladkarako** [comment]
oh! that makes sense that version DID broke recording! thanks! now I know why..

**Comment by di72nn** [comment]
You're welcome!

> that version DID broke recording

Don't forget to report details in [the app repo](https://gitlab.com/axet/android-call-recorder/-/issues/), if you can add something to what was already reported.
