### ISSUE TITLE
Does not always record

### ISSUE THREAD

**Issue by J4CKED** [Magisk-Modules-Repo/callrecorder-axet#8]
The app records very well. But not always. I have battery optimization turned off. 
I have no idea if the app turns itself off. 
During a call, when the call is not recording, there is no visible microphone icon in the status bar.
I had turned off notification: presistent icon in status bar. But today I decided to re-enable the "presistent icon" and test it.

Rooted Android 11.

**Comment by di72nn** [comment]
Sorry, I'm only dealing with the Magisk module (and the system permission), other app related issues should go to [the app repo](https://gitlab.com/axet/android-call-recorder/-/issues/).
