### ISSUE TITLE
Not lauch automatic on reboot (Android 12 & 13)

### ISSUE THREAD

**Issue by lavoie005** [Magisk-Modules-Repo/callrecorder-axet#9]
Hi, and big up for your free app.
on my Android 12 and now on Android 13. When we boot ur phone. we need to manually lauch the app or the app dont record call.
Thank for checking this problem.

**Comment by di72nn** [comment]
Hi, thanks for the report. This probably should be reported in [the app repo](https://gitlab.com/axet/android-call-recorder).
